# Generated by Django 3.0.6 on 2020-06-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200623_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='archived',
            new_name='archive',
        ),
    ]
