# Generated by Django 3.0.6 on 2020-06-24 15:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200623_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
