# Generated by Django 3.0.6 on 2020-08-30 17:40

from django.db import migrations
import editorjs_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20200624_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=editorjs_field.fields.EditorJSField(),
        ),
    ]
