# Generated by Django 3.0.6 on 2020-08-30 17:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20200830_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
